import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

const name = 'mangkoran'
export const sitleTitle = 'Welcome to ' + name + ' site!'

const LayoutHome = ({ children }: { children: React.ReactNode }) => {
    return (
        <>
            <div className={styles.containerDark}>
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>Welcome to my site!</h1>
                </main>
            </div>

            {children}
        </>
    )
}

export default LayoutHome
